service: cognito-nodejs
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: /api
          method: get
      - http:
          path: /api/signup
          method: post
      - http:
          path: /api/login
          method: post
      - http:
          path: /api/helloworld
          method: get
